name: animalmotionviz
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.3.11=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.13=h1a28f6b_2
  - pip=24.0=py311hca03da5_0
  - python=3.11.7=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=69.5.1=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.43.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - blinker==1.8.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - dash==2.17.0
      - dash-ag-grid==31.2.0
      - dash-bootstrap-components==1.6.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - dash-uploader==0.6.0
      - flask==3.0.3
      - idna==3.7
      - imageio==2.35.1
      - importlib-metadata==7.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markupsafe==2.1.5
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - opencv-contrib-python==4.9.0.80
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.4.0
      - plotly==5.22.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - requests==2.31.0
      - retrying==1.3.4
      - six==1.16.0
      - tenacity==8.3.0
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.3
      - zipp==3.18.1
prefix: /opt/anaconda3/envs/animalmotionviz
